services:
  - type: web
    name: sistema-backup
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "false"
